config/routes.rb
Rails.application.routes.draw do

  
  resources :leaderboards, only: [:index] do
    resources :entries, only: [:create, :index, :show, :destroy]
  end
  
  root to: "leaderboards#index"  
    

end

app/models/entity.rb
class Entity < ActiveRecord::Base
  self.per_page = 10
  has_many :entries, :dependent => :destroy
  has_many :leaderboards, :through => :entries
  accepts_nested_attributes_for :entries
  
  
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  self.per_page = 10  
  belongs_to :entity
  belongs_to :leaderboard

  default_scope { order('id DESC') }
  
  scope :find_entry_by_entity, -> (name) { joins(:entity).where(entities: {name: name}) }
  
  def rank
    Entry.where("score > ? and leaderboard_id = ?", score, leaderboard.id).count + 1
  end
end

app/models/leaderboard.rb
class Leaderboard < ActiveRecord::Base
  has_many :entities, :through => :entries
  has_many :entries, :dependent => :destroy

  def add_entry(entry_params)
    params = entry_params.symbolize_keys 
    entry = self.entries.find_entry_by_entity(params[:name]).first
    if !entry
      entity = Entity.where(name: params[:name]).first || Entity.create(name: params[:name])
      entry = entity.entries.create(leaderboard: self, score: params[:score])
    else
      entry.score = params[:score].to_i
    end
    entry.save
    entry
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from StandardError, :with => :error_render_method
    
  private
  
  def error_render_method(exception)
    if exception.kind_of?(ActionController::BadRequest)      
      render_400
    else
      render_404 
    end
  end
  
  def render_404
    respond_to do |format|
      format.html { render "public/404.html", :status => 404, :layout => false }
      format.all { render :status => 404, :nothing => true }
    end
  end
  
  def render_400
    respond_to do |format|
      format.html { render "public/400.html", :status => 400, :layout => false }
      format.all { render :status => 400, :nothing => true }
    end
  end
  
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  respond_to :html, :json
  before_filter :load_leaderboard

  def new

  end
  
  def index

  end

  def show
    @entity = Entity.find(params[:id])
    respond_with @entity
  end

  def create
  end

  def update
  end
  
  def destroy
    @entity = Entity.find(params[:id])    
    @entity.destroy

    respond_to do |format|
      format.html {
        redirect_to({ action: 'index'})
      }
      format.json {
        head :ok
      }
    end
  end
  
end 

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  respond_to :html, :json
  before_filter :load_leaderboard

  def new
    @entry = @leaderboard.entries.build()
  end
  
  def index
    page = params[:page] ? params[:page].to_i : 1
    per_page = params.fetch(:per_page, Entry.per_page).to_i

    raise ActionController::BadRequest.new("BadRequest", Exception.new('Max of 100 entries')) and return if per_page > 100    
    
    params[:per_page] = per_page
    @entries = @leaderboard.entries.paginate(page: page, per_page: per_page)    
    respond_with @entries
  end

  def show
    @entry = Entry.find(params[:id])
    respond_with @entry
  end

  def create
    @entry = @leaderboard.add_entry(entry_params)
    respond_to do |format|
      format.html {
        redirect_to leaderboard_entries_path(@leaderboard)
      }
      format.json {
        render json: EntrySerializer.new(@entry).to_json
      }
    end
  end

  def update
  end
  
  def destroy
    @entry = Entry.find(params[:id])    
    @entry.destroy

    respond_to do |format|
      format.html {
        redirect_to({ action: 'index'})
      }
      format.json {
        head :ok
      }
    end
  end
  

private

  def load_leaderboard
    @leaderboard = Leaderboard.find(params[:leaderboard_id]) if params[:leaderboard_id]
  end
  
  def entry_params
    params.require(:entry).permit(:name, :score)
  end
  
end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController
  respond_to :json

  def index
    @leaderboards = Leaderboard.all
  end

  def show
  end

  def create
  end

  def update
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/index.html.erb
<h3>Leaderboard: <%= @leaderboard.name %> </h3>
<div style="border: 1px solid black; padding:3px;">
  
  <%= form_tag leaderboard_entries_path(@leaderboard) do |f| %>
    <%= hidden_field_tag :_method, 'POST'  %>  

    <p><%= label_tag :entity_name %> <br />
    <%= text_field_tag "entry[name]" %></p>

    <p><%= label_tag :entry_score %> <br />
    <%= text_field_tag "entry[score]" %></p>
    
    <button type="submit" class="small" style="margin-right:16px;">Save Entry</button>    
  <% end %>
</div>
<div class="digg_pagination" style="margin-top:20px;">
    <div class="page_info">
      <%= page_entries_info @entries %>
      <label for="per_page">Per Page
      <input type="text" id="per_page" name="per_page" value="<%= (params[:per_page].blank? ? Entry.per_page :  params[:per_page].to_i) %>" onchange="if(this.value){window.location='?per_page='+this.value;}">
      </label>
    </div>
    <%= will_paginate @entries, params: {per_page: (params[:per_page].blank? ? Entry.per_page :  params[:per_page].to_i)} %>
</div>
  
<div class="row">
  <div class="large-4 columns"> NAME </div>
  <div class="large-3 columns"> SCORE </div>      
  <div class="large-2 columns"> RANK </div>       
  <div class="large-3 columns"> ACTION </div>           
</div>
<% @entries.each do |e| %>
  <div class="row">
    <div class="large-4 columns"><%= e.entity.name %></div>
    <div class="large-3 columns"><%= e.score %></div>      
    <div class="large-2 columns"><%= e.rank %></div>    
    <div class="large-3 columns">
      <%= link_to 'Show', leaderboard_entry_path(@leaderboard, e) %> | 
      <%= form_tag leaderboard_entry_path(@leaderboard, e), :style => "display:inline-block" do |f| %>
          <%= hidden_field_tag :_method, 'DELETE'  %>  
          <input type="submit" class="tiny" value='Delete' />
      <% end %>
    </div>             
  </div>
<% end %>

app/views/entries/show.html.erb
<%= link_to "BACK TO LEADERBOARD", leaderboard_entries_path(@entry.leaderboard) %>
<div class="row">
  <div class="large-6 columns"><%= @entry.entity.name %></div>
</div>
<div class="row">
  <div class="large-6 columns">Score</div><div class="large-6 columns"><%= @entry.score %></div>
</div>
<div class="row">
  <div class="large-6 columns">Rank</div><div class="large-6 columns"><%= @entry.rank %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id="main_content" class="row">
      <div class="columns large-12">

        <%= yield %>
       </div>
     </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/leaderboards/index.html.erb
<h1>Leaderboards</h1>
<% @leaderboards.each do |l| %>
  <div><%= link_to "LeaderBoard #{l.name} Entries", leaderboard_entries_path(l) %></div>
<% end %>